mysite/fraud/urls.py
from django.conf.urls import url
from fraud import views
app_name = "fraud"

urlpatterns = [
    #url(r'^$', views.front_page, name='front_page'),

    url(r'^index/', views.index, name='index'),
    url(r'^user_login/', views.user_login, name='user_login'),
    url(r'^itofficials/', views.itofficials, name='itofficials'),
    url(r'^generate_list/', views.generate_list, name='generate_list'),
    url(r'^new_case/', views.new_case, name='new_case'),
    url(r'^(?P<aadharno>[0-9]+)/', views.generate_report, name='generate_report'),
    url(r'^report_fraud/', views.report_fraud, name='report_fraud'),
    url(r'^lets_see/', views.lets_see, name='lets_see'),



]

mysite/mysite/urls.py
from django.conf.urls import url, include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path



urlpatterns = [
    path('admin/', admin.site.urls),
    url(r'^fraud/', include("fraud.urls" , namespace="fraud")),#managefraudroute
]

mysite/urls.py
from django.conf.urls import url, include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin



urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^fraud/', include("fraud.urls" , namespace="fraud")),#managefraudroute
]

    

mysite/fraud/models.py
from django.db import models
from django.contrib.auth.models import User
from django.core.validators import MinLengthValidator,MaxLengthValidator

class Aadhar(models.Model):
    aadhar_no = models.IntegerField(default=0, unique=True)
    name      = models.CharField(max_length=100,default = None)
    address   = models.TextField(max_length=100,default=None)

class Bank_formalities(models.Model):
    address =   models.TextField(max_length=100,default=None)
    ac_no   =   models.IntegerField(default=0,unique=True)
    aadhar_no = models.IntegerField(default=0, unique=True)


class tracked(models.Model):
    aadhar_no = models.IntegerField(default=0, unique=True)
    address   = models.TextField(max_length=100,default=None)


class bank_statement(models.Model):
    aadhar_no        =       models.IntegerField(default=0,unique=True)
    lEdu            =       models.IntegerField(default=0)
    hEdu            =       models.IntegerField(default=0)
    area            =       models.CharField(default=0,max_length=100)
    jewellery       =       models.IntegerField(default=0)
    cars            =       models.IntegerField(default=0)
    bikes           =       models.IntegerField(default=0)
    tax             =       models.IntegerField(default=0)
    credit          =       models.IntegerField(default=0)
    debit           =       models.IntegerField(default=0)


class Bank_details(models.Model):
    ac_no   =   models.IntegerField(default=0,unique=True)
    bank_statement  =   models.ForeignKey(bank_statement,on_delete=models.CASCADE)

class predicted_features(models.Model):
    aadhar_no        =       models.IntegerField(default=0,unique=True)
    lEdu            =       models.IntegerField(default=0)
    hEdu            =       models.IntegerField(default=0)
    area            =       models.CharField(default=0,max_length=100)
    jewellery       =       models.IntegerField(default=0)
    cars            =       models.IntegerField(default=0)
    bikes           =       models.IntegerField(default=0)
    tax             =       models.IntegerField(default=0)
    credit          =       models.IntegerField(default=0)
    debit           =       models.IntegerField(default=0)
    fraud           =       models.BooleanField(default=0)

class report(models.Model):
    aadhar_no        =       models.IntegerField(default=0,unique=False)
    reason           =       models.TextField(default='a')
    image            =       models.ImageField(upload_to='holidays/', default='default.jpg')
    amount           =       models.IntegerField(default=0,blank=True,null=True)

mysite/fraud/forms.py
from django.db import models
from django import forms
from fraud.models import User,report



class Authentic(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput())

    class Meta:
        model = User
        fields =("username","password","first_name","last_name","email",)

class Reporting(forms.ModelForm):
    class Meta:
        model = report
        fields = "__all__"

fraud/views.py
from django.http import HttpResponse,HttpResponseRedirect
from django.urls import reverse
import datetime
from django import template
from django.utils import timezone
from keras.models import load_model
import keras.backend as tf
from fraud.models import Aadhar,Bank_formalities,Bank_details,bank_statement,predicted_features,report
from django.shortcuts import render,get_object_or_404
from fraud.forms import Authentic,Reporting
from django.urls import reverse
import numpy as np
import os
import random
import pickle
from shutil import copyfile


from django.contrib.auth.decorators import login_required
from django.contrib.auth import authenticate,login,logout
#from codefundo.models import user_details,gov_fund,track_users
from datetime import datetime,date,timedelta
path = os.path.join(os.getcwd(),'fraud')

#madhuparna's code
import argparse
import torch
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim
from torchvision import datasets, transforms
import numpy as np
import torchvision
import torchvision.transforms as transforms
#madhuparna's code ends


def index(request):
    return render(request,"fraud/index.html")   

def itofficials(request):
    return render(request,"fraud/itofficials.html")

def getFamily(address):
    family = Bank_formalities.objects.filter(address = address)
    return family

def process(familyaadhar):
    bankStatements = [bank_statement.objects.filter(aadhar_no=aadhar)[0] for aadhar in familyaadhar]
        
    lEdu=0             
    hEdu=0                         
    jewellery=0        
    cars=0             
    bikes=0            
    tax=0              
    credit=0           
    debit=0
    
    for bankstatement in bankStatements:
        lEdu+= bankstatement.lEdu
        hEdu+= bankstatement.hEdu
        jewellery+= bankstatement.jewellery
        cars+= bankstatement.cars
        bikes+= bankstatement.bikes
        tax+= bankstatement.tax
        credit+= bankstatement.credit
        debit+= bankstatement.debit
        
     
    area = bankStatements[0].area
    aadhar = bankStatements[0].aadhar_no
    input_data = [lEdu,hEdu,jewellery,cars,bikes,tax,credit,debit]
    if area == 'slum':
        input_data += [1,0,0]
    elif area == 'middle':
        input_data += [0,1,0]
    else:
        input_data += [0,0,1]
    
    model = load_model(os.path.join(path, 'data.h5'))
    with open(os.path.join(path,'scaler'), 'rb') as sc:
        scaler = pickle.load(sc)
    
    print(input_data)
    input_data = np.array( [input_data])
    input_data = scaler.transform(input_data)
    
    input_data.dtype = 'float'
    print(type(input_data),input_data.shape)
    print(input_data)
    final_data = model.predict(input_data)
    print(final_data)

    #save all the final data in predicted features
    checkForPredict = predicted_features.objects.filter(aadhar_no=aadhar)
    
    if len(checkForPredict) == 0:
        form = predicted_features()
    else:
	    form = predicted_features.objects.filter(aadhar_no=aadhar)[0]
    # i = form.save(commit=False)

    #mark model as done
    citizen = Aadhar.objects.filter(aadhar_no=aadhar)[0]
    print(citizen)
    print(form)
    form.lEdu = lEdu
    form.hEdu = hEdu
    form.jewellery = jewellery
    form.cars = cars
    form.bikes = bikes
    form.tax = tax
    form.credit = credit
    form.debit = debit
    form.aadhar_no = aadhar
    form.fraud = True if final_data[0][0] > 0.5 else False
    form.save()
   
        
    #print(familyMembers) #family members of type bankformalities


def fraud_list(aadharno):
    allUsers = Aadhar.objects.filter(aadhar_no=aadharno)
    for user in allUsers:
 

        familyMembers = getFamily(user.address)
        process([familyMember.aadhar_no for familyMember in familyMembers])
    return allUsers[0].aadhar_no


    

def new_case(request):
   
    if request.method=="POST":
        aadharno=request.POST.get("aadharno")
        lEdu=request.POST.get("lEdu")
        hEdu=request.POST.get("hEdu")
        area=request.POST.get("area")
        jewellery=request.POST.get("jewellery")
        cars=request.POST.get("cars")
        bikes=request.POST.get("bikes")
        tax=request.POST.get("tax")
        credit=request.POST.get("credit")
        debit=request.POST.get("debit")
        #get the user with that particular aadhar number
        print(aadharno)
        
        #get the account number from the aadhar number for changing the data
        fraudUser = Bank_formalities.objects.filter(aadhar_no=aadharno) 
        for fraudUser in fraudUser:
            accountNo = fraudUser 
        
        #get the bank statements of that particular account number
        fraudAccount = Bank_details.objects.filter(ac_no = accountNo.ac_no)
        for fraudAccount in fraudAccount:
            print(fraudAccount.bank_statement)
        
        #till here fraudAccount contains the bank_statement details of the fraud account and we need to rewrite that
        fraudAccount.bank_statement.lEdu = lEdu
        fraudAccount.bank_statement.hEdu = hEdu
        fraudAccount.bank_statement.area = area
        fraudAccount.bank_statement.jewellery = jewellery
        fraudAccount.bank_statement.cars = cars
        fraudAccount.bank_statement.bikes = bikes
        fraudAccount.bank_statement.tax = tax
        fraudAccount.bank_statement.credit = credit
        fraudAccount.bank_statement.debit = debit
        fraudAccount.bank_statement.save()
        
        head = fraud_list(aadharno)
        print(head)
                
        predict = predicted_features.objects.filter(aadhar_no = head)
        return render(request,"fraud/generate_report.html",{"predict":predict})
    


    return render(request,"fraud/new_case.html",{},)



def user_login(request):
    if request.method=="POST":
        username=request.POST.get("username")
        password=request.POST.get("password")
        user=authenticate(username=username,password=password)
        if user:
            login(request,user)
            return HttpResponseRedirect(reverse("fraud:itofficials"))
        else:
            return HttpResponseRedirect(reverse("fraud:itofficials"))
    else:
        return render(request,"fraud/login.html")

def generate_list(request):
    predict = predicted_features.objects.all()
    return render(request,"fraud/generate_list.html",{"predict":predict})

def generate_report(request,aadharno):
    predict = predicted_features.objects.filter(aadhar_no = aadharno)
    return render(request,"fraud/generate_report.html",{"predict":predict})


def report_fraud(request):
    form = Reporting()
    if request.method == "POST":
        print("manan")
        form = Reporting(request.POST,request.FILES)
        
        if form.is_valid():
            form.save()
            return lets_see(request)
        else:
            print("not working")
    return render(request,"fraud/report_fraud.html",{"form":form})


def lets_see(request):
    form = report.objects.all()[0]
    print(form.image)
    path = os.path.join(os.path.join(os.getcwd(),'temp'), 'temp')
    print(path)
    # copyfile(form.image, os.path.join(path, os.path.basename(form.image)))
    print(os.path.join(os.getcwd(), 'media'))
    
    
    i=0

    for reports in report.objects.all():
        if i==11:
             break
        monument = GetPlace('./media/',i)
        i=i+1
        reports.amount = monument[1]
        print(reports.amount)
        print(monument[1])

        reports.save()
        print(reports.amount)
    # os.remove( os.path.join(path, os.path.basename(form.image)))
    print(monument)

    return render(request,"fraud/thanksReporting.html")

# code begins
def GetPlace(image_path,ind):
    
    monuments = ['Burkingham Palace','Burj Khalifa','Disney World','Eiffel Tower','Golden Gate Bridge','Great Wall of China','Pyramids','Statue of Liberty','Sydney Opera House','Taj Mahal']
    cost = [150000, 40000, 30000, 150000, 200000, 30000, 50000, 200000, 150000, 20000]
    device = torch.device('cuda:0' if torch.cuda.is_available() else 'cpu')
    data_transform = transforms.Compose([
            transforms.RandomSizedCrop(64),
            transforms.RandomHorizontalFlip(),
            transforms.Grayscale(num_output_channels=1),
            transforms.ToTensor(),
            transforms.Normalize(mean=[0.485, 0.456, 0.406],
                                 std=[0.229, 0.224, 0.225])
        ])
    class ConvNet(nn.Module):
        def __init__(self, num_classes=10):
            super(ConvNet, self).__init__()
            self.layer1 = nn.Sequential(
                nn.Conv2d(1, 16, kernel_size=5, stride=1, padding=2),
                nn.BatchNorm2d(16),
                nn.ReLU(),
                nn.MaxPool2d(kernel_size=2, stride=2))
            self.layer2 = nn.Sequential(
                nn.Conv2d(16, 32, kernel_size=5, stride=1, padding=2),
                nn.BatchNorm2d(32),
                nn.ReLU(),
                nn.MaxPool2d(kernel_size=2, stride=2))
            self.fc = nn.Linear(8192, num_classes)

        def forward(self, x):
            #print(x.shape)
            out = self.layer1(x)
            out = self.layer2(out)
            out = out.reshape(out.size(0), -1)
            out = self.fc(out)
            return out
    model = ConvNet(10)
    model.load_state_dict(torch.load('./model_wgs'))
    ans=[]
    for ite in range(20):
        #print(ite)
        test_data = datasets.ImageFolder(root=image_path,
                                                   transform=data_transform)
        test_loader = torch.utils.data.DataLoader(test_data,
                                                     batch_size=32, shuffle=True,
                                                     num_workers=4)
        model.eval()  # eval mode (batchnorm uses moving mean/variance instead of mini-batch mean/variance)
        with torch.no_grad():
            correct = 0
            total = 0
            for images, labels in test_loader:

mysite/fraud/templates/fraud/generate_list.html
{% extends 'base.html' %}
{% load staticfiles %}

{% block one %}

<p style="text-align: center;">
<strong><u>AADHAR NUMBER</u></strong>     <strong><u>FRAUD?</u></strong>  
<ul style="text-align: center;">
{% for predictions in predict %}<br>
<li>
 <a href="/fraud/{{predictions.aadhar_no}}">  {{predictions.aadhar_no}} </a>
   {{predictions.fraud}}<br><br>
</li>
   {% endfor %} 
</ul>
</p>
   {% endblock %}

mysite/fraud/templates/fraud/generate_report.html
{% extends 'base.html' %}
{% load staticfiles %}

{% block one %}
<ul style="text-align: center">
{% for predictions in predict %}
<li>
   <b><u>AADHAR NUMBER</u></b>{{predictions.aadhar_no}} <br>
   {{predictions.fraud}}<br>
   {{predictions}}<br>
</li>
   {% endfor %} 
</ul>
{% endblock %}

mysite/fraud/templates/fraud/index.html
{% extends 'base.html' %}
{% load staticfiles %}

{% block one %}

<div class="w3-container w3-padding-64 w3-red w3-grayscale w3-xlarge" id="about">
        <div class="w3-content">
          <h1 class="w3-center w3-jumbo" style="margin-bottom:64px">About</h1>
          <p>Income Tax Fraud Detector is a web application used for income tax fraud detection using Artificial Intelligence and Machine Learning. This application is an efficient and smart solution to a major problem prevalent in our country.</p>
          <!-- <p><strong>The Chef?</strong> Mr. Italiano himself<img src="/w3images/chef.jpg" style="width:150px" class="w3-circle w3-right" alt="Chef"></p>
          <p>We are proud of our interiors.</p>
          <img src="/w3images/onepage_restaurant.jpg" style="width:100%" class="w3-margin-top w3-margin-bottom" alt="Restaurant">
          <h1><b>Opening Hours</b></h1>
          
          <div class="w3-row">
            <div class="w3-col s6">
              <p>Mon & Tue CLOSED</p>
              <p>Wednesday 10.00 - 24.00</p>
              <p>Thursday 10:00 - 24:00</p>
            </div>
            <div class="w3-col s6">
              <p>Friday 10:00 - 12:00</p>
              <p>Saturday 10:00 - 23:00</p>
              <p>Sunday Closed</p>
            </div>
          </div> -->
          
        </div>
      </div>      
{% endblock %}

mysite/fraud/templates/fraud/itofficials.html
{% extends 'base.html' %}
{% load staticfiles %}

{% block one %}

<div id="contact">
        <div class="w3-modal-content w3-animate-zoom">
          <div class="w3-container w3-black">
              <h1>Welcome Officer</h1>
           </div>
           <div class="w3-container">
            <p>Choose your option:</p>


<a href="{% url "fraud:new_case" %}"><p><input class="w3-input w3-padding-16 w3-border" type="button" value="OPEN NEW CASE"></p></a>
<a href="{% url "fraud:generate_list" %}"><p><input class="w3-input w3-padding-16 w3-border" type="button" value="GENERATE LIST"></p></a>
</div>
{% endblock %}

mysite/fraud/templates/fraud/login.html
{% extends 'base.html' %}
{% load staticfiles %}

{% block one %}
<br>
<div id="contact">
   <div class="w3-modal-content w3-animate-zoom">
     <div class="w3-container w3-black">
         <h1>Official Login</h1>
      </div>
      <div class="w3-container">
        <p>Enter your username and password:</p>
         <form class="form-horizontal" action="{% url 'fraud:user_login' %}" method="POST">
         {% csrf_token %}
         <p><input class="w3-input w3-padding-16 w3-border" type="text" placeholder="Name"></p>
      <p><input class="w3-input w3-padding-16 w3-border" type="password" placeholder="Password"></p>
      <p><button class="w3-button" style="border:black 1px solid;" type="submit">LogIn</button></p>
   </form>   
   </div>
     </div>
    </div>
{% endblock %}

mysite/fraud/templates/fraud/new_case.html
{% extends 'base.html' %}
{% load staticfiles %}

{% block one %}
<br>

<div id="contact">
    <div class="w3-modal-content w3-animate-zoom">
      <div class="w3-container w3-black">
          <h1>Generate New Case</h1>
      </div>
      <div class="w3-container">
      <form class="form-horizontal" action="{% url "fraud:new_case" %}" method="POST">
      {% csrf_token %}
      <p><input class="w3-input w3-padding-16 w3-border" type="text" placeholder="Enter Aadhar Number"></p>
      <p><input class="w3-input w3-padding-16 w3-border" type="text" placeholder="Amount spent on lower education"></p>
      <p><input class="w3-input w3-padding-16 w3-border" type="text" placeholder="Amount spent on lower education"></p>
      <p><input class="w3-input w3-padding-16 w3-border" type="text" placeholder="Cost of living according to locality"></p> 
     <datalist id="hosting-plan">
        <option value="slums">slums</option>
        <option value="middle">middle</option>
        <option value="posh">posh</option>
    </datalist>
    <p><input class="w3-input w3-padding-16 w3-border" type="text" placeholder="Amount spent on jewelery"></p>
    <p><input class="w3-input w3-padding-16 w3-border" type="text" placeholder="Number of cars"></p>
    <p><input class="w3-input w3-padding-16 w3-border" type="text" placeholder="Number of bikes"></p>
    <p><input class="w3-input w3-padding-16 w3-border" type="text" placeholder="Enter tax paid"></p>
    <p><input class="w3-input w3-padding-16 w3-border" type="text" placeholder="Enter miscellaneous credit details"></p>
    <p><input class="w3-input w3-padding-16 w3-border" type="text" placeholder="Enter miscellaneous debit details"></p>
    <p><button class="w3-button" style="border:black 1px solid;" type="submit">Submit Details</button></p>    </form>
      </div>
        </div>
        </div>
{% endblock %}

mysite/fraud/templates/fraud/report_fraud.html
{% extends 'base.html' %}
{% load staticfiles %}

{% block one %}
<div id="contact">
    <div class="w3-modal-content w3-animate-zoom">
      <div class="w3-container w3-black">
          <h1>Fraud Reporting</h1>
       </div>
       <div class="w3-container">
         <p>Enter the suspected details of the individual you want to report:</p>
     <form style="color:black" class="form-horizontal" action="{% url 'fraud:report_fraud' %}" method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        <p><input class="w3-input w3-padding-16 w3-border" type="text" placeholder="Enter AADHAR Number"></p>
      Upload Image: {{form.image}}
      <p><input class="w3-input w3-padding-16 w3-border" type="text" placeholder="Enter reason why you feel the individual is a fraud"></p>{{form.reason}}
      {{form.Amount}}
      <p><button class="w3-button" style="border:black 1px solid;" type="submit">Submit Details</button></p>
    </form>
</div>
{% endblock %}

mysite/fraud/templates/fraud/thanksReporting.html
{% extends 'base.html' %}
{% load staticfiles %}

{% block one %}

<h1>Thanks for Submitting Your Response</h1>

{% endblock %}